apiVersion: v1
kind: Service
metadata:
  name: scylla-operator-webhook-service
  namespace: scylla-operator-system
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    control-plane: controller-manager