apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: scylla-manager-controller
  name: scylla-manager-controller
  namespace: scylla-manager-system
spec:
  selector:
    matchLabels:
      control-plane: scylla-manager-controller
  serviceName: controller-service
  template:
    metadata:
      labels:
        control-plane: scylla-manager-controller
    spec:
      containers:
        - args:
            - manager-controller
            - --log-level=debug
          command:
            - /scylla-operator
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: scylladb/scylla-operator:v1.0.0
          imagePullPolicy: IfNotPresent
          name: scylla-manager-controller
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            name: scylla-manager-manager-config-2tfggm9842
          name: scylla-manager-config-volume