apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla-manager-scylla-manager
  namespace: scylla-manager-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylla-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scylla-manager
    spec:
      containers:
        - args:
            - --config-file=/mnt/etc/scylla-manager/scylla-manager.yaml
          command:
            - /usr/bin/scylla-manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: scylladb/scylla-manager:2.2.2
          imagePullPolicy: IfNotPresent
          name: scylla-manager
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - mountPath: /mnt/etc/scylla-manager
              name: scylla-manager-config-volume
      volumes:
        - configMap:
            name: scylla-manager-manager-config-2tfggm9842
          name: scylla-manager-config-volume