apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: simple-scylla-cluster
  namespace: scylla
spec:
  version: 4.2.0
  agentVersion: 2.2.1
  developerMode: true
  datacenter:
    name: us-ease-1
    racks:
      - name: us-east-1a
        scyllaAgentConfig: scylla-agent-config
        scyllaConfig: scylla-config
        members: 1
        storage:
          capacity: 5Gi
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 2
            memory: 2Gi