apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla-manager-cluster
  namespace: scylla-manager-system
spec:
  agentVersion: 2.2.1
  datacenter:
    name: manager-dc
    racks:
      - members: 1
        name: manager-rack
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        scyllaAgentConfig: scylla-agent-config
        scyllaConfig: scylla-config
        storage:
          capacity: 10Gi
  developerMode: false
  version: 4.3.0