apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: scylla-operator-system/scylla-operator-serving-cert
  name: scylla-operator-mutating-webhook-configuration
webhooks:
  - clientConfig:
      service:
        name: scylla-operator-webhook-service
        namespace: scylla-operator-system
        path: /mutate-scylla-scylladb-com-v1-scyllacluster
    failurePolicy: Fail
    name: webhook.scylla.scylladb.com
    rules:
      - apiGroups:
          - scylla.scylladb.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - scyllaclusters
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None