apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
  name: scylla-operator-controller-manager
  namespace: scylla-operator-system
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - operator
            - --log-level=debug
          command:
            - /scylla-operator
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: scylladb/scylla-operator:v1.0.0
          imagePullPolicy: IfNotPresent
          name: manager
          ports:
            - containerPort: 443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert