apiVersion: v1
kind: Service
metadata:
  labels:
    app: scylla-manager
  name: scylla-manager-manager-service
  namespace: scylla-manager-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5080
  selector:
    app: scylla-manager