apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: scylla-operator-system/scylla-operator-serving-cert
  name: scylla-operator-mutating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: scylla-operator-webhook-service
        namespace: scylla-operator-system
        path: /mutate-scylla-scylladb-com-v1-scyllacluster
    failurePolicy: Fail
    name: webhook.scylla.scylladb.com
    rules:
      - apiGroups:
          - scylla.scylladb.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - scyllaclusters
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: scylla-operator-system/scylla-operator-serving-cert
  creationTimestamp: null
  name: scylla-operator-validating-webhook-configuration
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: scylla-operator-webhook-service
        namespace: scylla-operator-system
        path: /validate-scylla-scylladb-com-v1-scyllacluster
    failurePolicy: Fail
    name: webhook.scylla.scylladb.com
    rules:
      - apiGroups:
          - scylla.scylladb.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - scyllaclusters